[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.24"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
arcTestnet = "https://rpc.testnet.arc.network"

[etherscan]
arcTestnet = { key = "", url = "https://testnet.arcscan.app/api" }
